name: Android Debug APK

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (retry)
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 6
          retry_wait_seconds: 20
          command: |
            rm -rf repo && mkdir repo
            git init repo
            cd repo
            git remote add origin https://github.com/${{ github.repository }}.git
            git fetch --depth=1 origin ${{ github.ref_name }}
            git checkout FETCH_HEAD

      - name: Move repo to workspace
        run: |
          shopt -s dotglob
          rm -rf ./* ./.??* || true
          mv repo/* .
          rm -rf repo

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: yinn-zivpn-manager-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk